### ISSUE TITLE
增加Dockerfile通过docker简化部署

### ISSUE THREAD

**Issue by JermineHu** [TruthHun/BookStack#13]
1. 你当前使用的是哪个版本的 BookStack?
### 最新版本

2. 你当前使用的是什么操作系统?

### window10
3. 你是如何操作的？

### 下载编译，本地运行
4. 你期望得到什么结果?
### 从docker仓库进行部署，简化部署统一环境

5. 当前遇到的是什么结果?

### 只能通过编译成不同平台的二级制文件然后进行部署

**Comment by bubbleatgit** [comment]
不太完善版本，不过凑合能用吧。。
```
FROM alpine:latest

LABEL maintainer="tingshow163@gmail.com"

ENV CHINESE_DEPS \
        libreoffice \
        imagemagick \
        python \
        poppler-utils \
        xdg-utils \
        xz

# ADD ALPINE CHINESE MIRROR
RUN set -xe \
        \
        && echo -e "https://mirrors.tuna.tsinghua.edu.cn/alpine/v3.7/main\nhttps://mirrors.tuna.tsinghua.edu.cn/alpine/v3.7/community" > /etc/apk/repositories \
        \
        && echo /etc/apk/repositories \
        \
        && apk update \
        && apk add --no-cache --virtual .base-deps curl unzip tzdata \
        && cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
        && echo "Asia/Shanghai" > /etc/timezone
#       && apk add --no-cache --virtual .chinese-deps  ${CHINESE_DEPS} 

#RUN set -xe \
#       \
#       && mkdir -p /opt/calibre \
#        && curl -fsSL https://download.calibre-ebook.com/linux-installer.py | python -c "import sys; main=lambda:sys.stderr.write('Download failed\n'); exec(sys.stdin.read()); main()" \
#        && ebook-convert --version
#
#
RUN set -xe \
#       && curl -LO https://github.com/TruthHun/BookStack/releases/download/v1.3.1/BookStack.V1.3.1_linux_amd64.zip \
        && curl -o BookStack.V1.3.1_linux_amd64.zip "http://files.git.oschina.net/group1/M00/03/BA/PaAvDFsFZFSAbAOQASRKYadPGpU894.zip?token=e66b7c446e21d9dc9f3f67c409934cf1&ts=1529751362&attname=BookStack.V1.3.1_linux_amd64.zip" \
        && ls -al \
        && unzip BookStack.V1.3.1_linux_amd64.zip \
        && mkdir -p /var/www \
        && cp -arf BookStack.V1.3.1_linux_amd64/* /var/www \
        && ls -al /var/www

RUN set -ex \
        && rm -rf BookStack.V1.3.1_linux_amd64*


WORKDIR /var/www/
VOLUME /var/www/config

CMD [ "./BookStack install" ]
```

## docker-compose.yaml

```
version: "3"
  
services:
  bookstack:
    image: "bookstack:latest"
    ports:
      - "8181:8181"
    volumes:
      - "/var/www/bookstack/conf:/var/www/conf"
    links:
      - mysql
    restart: always

  mysql:
    image: "mysql:5.7"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "111111111"
      MYSQL_DATABASE: "bookstack"
      MYSQL_USER: "bookstack"
      MYSQL_PASSWORD: "bookstack123"
    volumes:
      - "/var/lib/mysql:/var/lib/mysql"
    restart: always
```
