### ISSUE TITLE
Docker容器部署BookStack访问页面空白问题处理

### ISSUE THREAD

**Issue by wwwxeb** [TruthHun/BookStack#137]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 BookStack?
2.9

2. 你当前使用的是什么操作系统?
linux

3. 你是如何操作的？
docker部署，使用了下面的镜像：
willdockerhub/bookstack 
https://hub.docker.com/r/willdockerhub/bookstack 

4. 你期望得到什么结果?
部署成功运行

5. 当前遇到的是什么结果?
部署成功，访问时页面空白，查看日志提示表不存在

6. 解决
问题我已经解决了，发出来给大家做个参考。
查看日志得知表不存在，由于我用docker部署的mysql，所以使用了docker自定义网络来实现docker容器间的访问，因此在配置文件配置的数据库host是自定义的mysql域名。
但是容器刚创建的时候还未加入自定义网络中，导致容器首次运行无法自动创建数据库，接着加入自定义网络，日志虽然提示数据库连接成功，但是BookStack并不会再次创建数据库表，这时候查看数据库是空白的。
解决方法有两个，先使用docker内部的数据库IP配置创建容器，然后再修改为容器自定义host
创建容器的时候指定加入网络。

**Comment by LiYouliang** [comment]
我也是遇到这个问题，而且我是用docker-compose部署的，但docker-compose里不是已经用depends_on指定了先后依赖关系的吗？为什么还会有问题？

```
services:
  bookstack:
    image: "willdockerhub/bookstack:v2.10_node"
    container_name: bookstack
    ports:
      - "8181:8181"
    depends_on:
      - db
    restart: always
    networks:
      - bookstack
```
